humhub/calendar

models/CalendarEntry.php
In that case, use only the given limit. This allows to show a fixed
number of upcoming events, no matter when they happen.
=> Handle 0 days in future as a special case in getUpcomingEntries()

models/CalendarEntry.php, views/global/index.php
I've fixed three problems that I have using this module:
* In main calendar page, event creation modal dialog doesn't show selected date. The problem is the name of the GET parameters (start_time instead of start_datetime and end_time of end_datetime). 
*  CalendarEntry's participation mode default value always override database value. I removed the variable declaration, set the participation mode default value in a new init function and it works.
* My mother tongue isn't English, as you probably guessed :). Dates in Spanish uses the format dd/mm/yyyy, but the DateTime class constructor can't parse it properly. So, I've used the formatter's dateFormat to guess user format and used in \DateTime::createFromFormat function. I think this could be done better, but at least works when the …
=> Three fixes 

models/CalendarEntry.php
getParticipantCount without an explicit state could be misleading: who
exactly are we counting?
We'd be counting any user with a ParticipantStatus associated with
that event. That includes both `declined` and `accepted` statuses. A
count on the combination of this is rarely useful.
Luckily, getParticipantCount is always called with this state
parameter specified. Let's remove the optional part for clarity.
=> Cleanup: remove optional part of parameter

.travis.yml, .travis/install-dependencies.sh, .travis/setup-humhub.sh, tests/codeception/acceptance.suite.yml
Enable Travis-CI for Calendar-Module
- Build as matrix against PHP 5.6, 7.0, 7.1 and Humhub master / v1.3-dev
- Allow failure for v1.3-dev
Please enable Travis-CI for this repository before merge. Current build for my fork: https://travis-ci.org/danielkesselberg/humhub-modules-calendar
=> Enable Travis-CI 

controllers/GlobalController.php
The global calendar did not have a page title set. Use "Calendar" (as
appropriately translated).
=> Add a page title to the global calendar

models/CalendarEntry.php
#198 
in recurrence mode, `max_participant` did not sync to its parent and it was always empty, so it cause `checkMaxParticipant()` in `canRespond()` always return true.
=> sync max_participants to parent entry #198

widgets/views/wallEntry.php
Not a huge thing, but I modified the calendar module for an own installation where I changed the "getColor()" method and was surprised that the color was not used in the stream...
=> Use Getter to access color property of calendar entry

docs/README.md
The current link points to the "Meeting" extension, not the "External Calendar" extension
=> Fix link to "External Calendar" extension

docs/CHANGELOG.md, migrations/m220422_104254_double_location_length.php, models/CalendarEntry.php
The 64 character limit does not allow to paste Zoom links that include a longer meeting password.
In my specific use-case the link was 73 characters long.
I have chosen 128 rather randomly, followed by the "in doubt double capacity" principle.
=> Double length of Location field

views/entry/edit-basic.php
I stumbled over the hard-coded value after deploying version 1.2.1 and realizing #283 is not yet fixed.
I overlooked this because GitHub does not return a match for this file when searching for `64`.
@luke- 
I am wondering if a better approach would be to grab the length for the location field (and possible the `Title` field) from the data model instead of hard-coding here?
=> Double length for location field in edit dialog

docs/CHANGELOG.md, models/forms/CalendarEntryForm.php, models/forms/CalendarEntryParticipationForm.php, models/reminder/ReminderProcessor.php, module.json
Issue: https://github.com/humhub/calendar/issues/326
=> Don't send notifications for canceled events

docs/CHANGELOG.md, helpers/CalendarUtils.php, models/CalendarEntry.php
Fix `null` value in first param of `new DateTime()` on PHP 8.1
=> Fix null in DateTime on PHP 8.1

Events.php, docs/CHANGELOG.md, module.json
Fix similar issue as https://github.com/humhub/cfiles/issues/198
=> Fix memory usage on integrity check

docs/CHANGELOG.md, models/participation/CalendarEntryParticipation.php
The previous behaviour only send notifications about event updates/ changes to accounts that had responded with `Maybe` or `Accepted` to an event.
This change also sends notifications to accounts still in `Invited` status, aka accounts who have not responded to the invite.
I successfully tested that accounts who have declined participation will not receive an update notification.
Background:
When an event gets changed (e.g new date & time) invitees how have not replied to the event will not get notified about the change in date & time.
With the changes around adding ICS files to calendar notifications (#435 and #439) this can lead to external calendars not receiving updated ICS files with the new date & time. Hence those calendars start being out of sync.
=> Send event update notifcation to invitees

docs/CHANGELOG.md, notifications/ForceAdd.php
#436 added ICS attachments to Invite notification emails.
The code path only triggers when individual members are being invited to an event, but not if `Add all Space members with status` was set to `Invited`.
This PR is the equivalent of #436 for these types of invitation notifications.
=> Attach ICS files to "forced invites"

integration/BirthdayCalendarQuery.php
Issue: https://github.com/humhub/calendar/actions/runs/7583134176/job/20654131536#step:25:253
Here https://github.com/humhub/humhub/pull/6745/files#diff-ba7b8761764d032b4ad21f00cd5a99380bfd7da056e9c5c90702738a6983f5d9R29 the method `friendship\Module::getIsEnabled()` was replaced with new `friendship\Module::isFriendshipEnabled()`.
I have decided to use `->settings->get('enable')` instead of new `->isFriendshipEnabled()` because of error on versions older 16.
Same issues should be fixed in the modules `cfiles` and `tasks`.
=> Fix tests for core v1.16+

docs/CHANGELOG.md, interfaces/VCalendar.php
closes https://github.com/humhub/calendar/issues/459
This simply adds 'STATUS:CANCELLED' to the ICS file for a cancelled event. 
(It also affects calendar exports via the external_calendar module).
Tested with https://icalendar.org/validator.html - no errors found.
Note: I have also added the changelog for #457 because I missed that there.
=> Enh canceled vcalendar

controllers/EntryController.php, docs/CHANGELOG.md, notifications/BaseEventNotification.php, notifications/EventUpdated.php, notifications/MarkAttend.php, notifications/ParticipantAdded.php, notifications/ReopenedEvent.php
https://github.com/humhub/humhub-internal/issues/284
=> New notification when user marks "Attend" and attach ICS files

notifications/EventUpdated.php, notifications/MarkAttend.php, notifications/ParticipantAdded.php, notifications/ReopenedEvent.php, notifications/base/EventNotification.php
https://github.com/humhub/humhub-internal/issues/291
=> Fix base event notification

Module.php, config.php, docs/CHANGELOG.md, helpers/Url.php
- `/calendar` as URL for the global calendar
- `/s/space/calendar` for the space calendar
- `/u/user/calendar` for the profile calendar
Those URLs are more user friendly (easy to remember and share) and SEO friendly.
The old URLs (`/calendar/global/index` and `/s/space/calendar/view`) still work.
**To do:**
=> Improved URLs

docs/CHANGELOG.md, helpers/Url.php
This should fix https://github.com/humhub/humhub/issues/7393
I can reproduce the error: When the start page is a custom page the generated global calendar URL in the top navigation is `https://DOMAIN/custom_pages/calendar/global` which is obviously wrong.
(The mistake happened in https://github.com/humhub/calendar/pull/520)
=> fix wrong URL (use absolute url instead of relative)

docs/CHANGELOG.md, widgets/CalendarFilterBar.php
This PR show the "Filter by types" filter only if a list a type is available, either globally and for a space (if displayed in the global calendar), or for the current space.
=> Enh: Show the "Filter by types" filter only if a list a type is available

docs/CHANGELOG.md
I made a mistake in the changelog while merging branches (https://github.com/humhub/calendar/pull/514/commits/0fe8ab3a1f75edd739974c2fe66f03bee3de047f). So the entry for PR #514 got into the wrong version, sorry.
=> Fix CHANGELOG.md
