humhub/calendar

controllers/EntryController.php
models/CalendarEntry.php
models/ICS.php
widgets/views/wallEntry.php

I'm very new to this (my first time participating in any open-source project), so please feel free to correct/tell me to correct anything that requires it. I'm not sure of HumHub conventions, such as where to store helper files (such as the ICS.php file).

Added a "Download ICS" button to the Calendar widget

---

.travis.yml
.travis/install-dependencies.sh

- Adjust matrix for 1.3 (master) / 1.2 (v1.2)
- Install composer-asset-plugin only for 1.2
Travis-CI: https://travis-ci.org/danielkesselberg/humhub-modules-calendar

Update .travis.yml for 1.3

---

docs/CHANGELOG.md
migrations/m201013_172104_add_calendar_entry_location.php
models/CalendarEntry.php
models/forms/CalendarEntryForm.php
module.json
views/entry/edit-basic.php
widgets/views/wallEntry.php

Issue: https://github.com/humhub/humhub-modules-calendar/issues/3

New attribute “Location” for calendar entry

---

docs/CHANGELOG.md
module.json
widgets/WallEntry.php
widgets/views/wallEntry.php

Issues: https://github.com/humhub/humhub-modules-calendar/issues/208 and https://github.com/humhub/tasks/issues/30

Wall Stream Layout Migration

---

controllers/GlobalController.php
docs/CHANGELOG.md

Issue: https://github.com/humhub/humhub-modules-calendar/issues/224

Hide space with disabled module on chooser modal window

---

docs/CHANGELOG.md
models/SnippetModuleSettings.php
module.json

Issue: https://github.com/humhub/humhub-modules-calendar/issues/218

Change snippet default sort

---

docs/CHANGELOG.md
models/reminder/CalendarReminder.php
module.json

Issue: https://github.com/humhub/cfiles/issues/114

Fix for PHP8 - Deprecate required parameters after optional parameters

---

docs/CHANGELOG.md
models/forms/CalendarEntryForm.php

Issue: https://github.com/humhub/calendar/issues/246

Fix error displaying of empty date fields

---

Events.php
controllers/GlobalController.php
docs/CHANGELOG.md
models/SnippetModuleSettings.php
module.json
widgets/ConfigureButton.php
widgets/FullCalendar.php

Issue: https://github.com/humhub/humhub/issues/4558

Deprecate CompatModuleManager

---

docs/CHANGELOG.md
widgets/views/wallEntry.php

Issue: https://github.com/humhub/calendar/issues/254

Fix wall stream entry icons color

---

controllers/EntryController.php
docs/CHANGELOG.md
models/CalendarEntry.php
widgets/EntryParticipants.php

Issue: https://github.com/humhub/calendar/issues/265

Disable to change participant status when event is over

---

docs/CHANGELOG.md
interfaces/CalendarService.php

Issue: https://github.com/humhub/calendar/issues/233

Fix recurrence events visibility in snippet

---

controllers/ViewController.php
docs/CHANGELOG.md
interfaces/event/AbstractCalendarQuery.php
module.json
tests/codeception/acceptance.suite.yml
tests/codeception/unit/recurrence/RecurrenceServiceTest.php

Issue: https://github.com/humhub/calendar/issues/241

Fix filter "I'm attending" for recurrence events

---

docs/CHANGELOG.md
helpers/CalendarUtils.php
models/forms/CalendarEntryForm.php

Issue: https://github.com/humhub/calendar/issues/276

Fix saving time when system date is transition to daylight

---

docs/CHANGELOG.md
views/entry/modal.php

https://github.com/humhub/calendar/issues/269

Add Close Button to Calendar Entry Modal

---

docs/CHANGELOG.md
jobs/ForceParticipation.php
models/forms/CalendarEntryParticipationForm.php
models/participation/CalendarEntryParticipation.php
tests/codeception/acceptance/CreateSpaceEntryCest.php

Issue: https://github.com/humhub/calendar/issues/294

Fix status on inviting of all space members

---

views/config/snippet.php
widgets/views/participantAddForm.php

Issue: https://github.com/humhub/calendar/issues/293

Fix missed translations

---

docs/CHANGELOG.md
models/forms/CalendarEntryForm.php
views/entry/edit-basic.php

Issue: https://github.com/humhub/calendar/issues/300

Fix default reminders for new creating calendar entry

---

controllers/EntryController.php
docs/CHANGELOG.md
module.json
views/entry/modal-participants.php
widgets/ParticipantsLink.php
widgets/WallEntry.php
widgets/views/participantAddForm.php
widgets/views/participantList.php

Fix participants settings for user without permissions

Fix participants list visibility

---

docs/CHANGELOG.md
jobs/ForceParticipation.php

Issue: https://github.com/humhub/calendar/issues/316

Fix invitation of space members

---

.github/workflows/marketplace-upload.yml
.github/workflows/php-test-develop.yml
.github/workflows/php-test-master.yml
.github/workflows/php-test-v1.10.yml
.github/workflows/php-test.yml

Issue: https://github.com/humhub/team_tasks/issues/222

Reusable test actions

---

widgets/DeleteLink.php

Issue: https://github.com/humhub/wording/issues/111

Fix wording "Delete"

---

docs/CHANGELOG.md
jobs/ForceParticipation.php
module.json

Issue: https://github.com/humhub/calendar/issues/341

Don't invite disabled users

---

helpers/CalendarUtils.php
helpers/RecurrenceHelper.php

Related issue: https://github.com/humhub/humhub/pull/6182

Avoid error on pass `null` to `DateTime::createFromFormat()`

---

interfaces/recurrence/AbstractRecurrenceQuery.php
models/CalendarEntry.php
tests/codeception/api/EventCest.php
tests/codeception/unit/recurrence/RecurrenceEditTest.php

Issue: https://github.com/humhub/humhub-internal/issues/31#issuecomment-1521953731

Soft deletion and restoring

---

Events.php
Module.php
docs/CHANGELOG.md

Issue: https://github.com/humhub/humhub-internal/issues/40

Hard delete records on disable module

---

controllers/AbstractConfigController.php
docs/CHANGELOG.md
helpers/Url.php
models/DefaultSettings.php
models/forms/BasicSettings.php
models/forms/CalendarEntryForm.php
models/participation/FullCalendarSettings.php
models/participation/ParticipationSettings.php
models/reminder/forms/ReminderSettings.php
module.json
tests/codeception/acceptance/SettingsCest.php
views/common/_settings_basic.php
views/common/defaultConfig.php
views/entry/edit-basic.php

Issue: https://github.com/humhub/team_tasks/issues/276#issuecomment-1527948899

Added support for hidden calendar entries in stream

---

docs/CHANGELOG.md
models/CalendarEntry.php
widgets/views/wallEntry.php

Issue: https://github.com/humhub/calendar/issues/394

Enh #394: If the location is an URL, convert it to a clickable link

---

docs/CHANGELOG.md
models/CalendarEntry.php
module.json

Issue: https://github.com/humhub/calendar/issues/415

Fix recurring event visibility on stream

---

docs/CHANGELOG.md
interfaces/recurrence/RecurrenceFormModel.php

Issue: https://github.com/humhub/calendar/issues/380

Fix visibility of last recurring event with defined end date

---

docs/CHANGELOG.md
models/CalendarEntry.php

https://github.com/humhub/calendar/issues/382

Allow inviting by users who can manage a calendar entry

---

controllers/AbstractConfigController.php
docs/CHANGELOG.md
helpers/Url.php
views/common/_calendarTypeItem.php

Issue: https://github.com/humhub/calendar/issues/379

Allow managing of global event types from container side

---

controllers/ConfigController.php
controllers/ContainerConfigController.php
controllers/FullCalendarController.php
controllers/GlobalController.php
controllers/IcalController.php
controllers/ReminderController.php
docs/CHANGELOG.md
module.json

https://github.com/humhub/humhub-internal/issues/113

Fix visibility of the method `Controller::getAccessRules()`

---

controllers/ConfigController.php
controllers/ContainerConfigController.php
controllers/FullCalendarController.php
controllers/GlobalController.php
controllers/IcalController.php
controllers/ReminderController.php
docs/CHANGELOG.md
module.json

Revert "Fix visibility of the method `Controller::getAccessRules()`"

---

config.php
controllers/IcalController.php
docs/CHANGELOG.md
interfaces/VCalendar.php
models/CalendarEntry.php
notifications/Invited.php

Issue: https://github.com/humhub/calendar/issues/435

Attach ICS file to invitation email

---

controllers/GlobalController.php
docs/CHANGELOG.md
views/global/selectContainerModal.php

Issue: https://github.com/humhub/calendar/issues/437

Fix #437: Hide the profile calendar if the module is not available for users

---

controllers/EntryController.php
docs/CHANGELOG.md
models/CalendarEntry.php
models/forms/CalendarEntryParticipationForm.php
models/participation/CalendarEntryParticipation.php
models/participation/ParticipationSettings.php
tests/codeception/unit/reminder/ReminderProcessTest.php
widgets/ParticipantItem.php

https://github.com/humhub/calendar/issues/434

Fix adding of all space members with status

---

docs/CHANGELOG.md
models/forms/CalendarEntryForm.php

https://github.com/humhub/calendar/issues/440

Extend list of fields for updating of sequence

---

docs/swagger/calendar.yaml
helpers/RestDefinitions.php

Added Location to RestDefinitions to resolve issue #467

Update RestDefinitions.php with location

---

controllers/ContainerConfigController.php

https://github.com/humhub/humhub-internal/issues/184

Improve container module settings

---

docs/CHANGELOG.md
migrations/m240319_152508_fix_notification.php
module.json

https://github.com/humhub/humhub-internal/issues/193#issuecomment-2007441063

Fix obsolete notifications

---

docs/CHANGELOG.md
views/global/index.php

Idea from https://community.humhub.com/content/perma?id=277000

Enh: Add footer to global calendar

---

docs/CHANGELOG.md
models/CalendarEntry.php
module.json

https://github.com/humhub/calendar/issues/474

Fix checking for past event when it is created from different time zone

---

docs/CHANGELOG.md
views/global/index.php
widgets/CalendarFilterBar.php
widgets/views/calendarFilterBar.php

https://github.com/humhub/calendar/issues/478

Revert missed controls on space calendar

---

widgets/views/calendarTypeLegend.php

https://github.com/humhub/wording/issues/158

Wording "Event Types"

---

docs/CHANGELOG.md
notifications/EventUpdated.php

https://github.com/humhub/calendar/issues/500

Fix notification message about updated event

---

widgets/views/upcomingEvents.php

Bug after PR https://github.com/humhub/calendar/pull/502

Fix using of event formatter

---

docs/CHANGELOG.md
views/config/menu.php
views/config/snippet.php
views/global/selectContainerModal.php

https://github.com/humhub/humhub-internal/issues/372

[v1.17] Update Active Form for Bootstrap 5

---

docs/CHANGELOG.md
helpers/Url.php

https://github.com/humhub/calendar/pull/516

Fixed url for global calendar when prettyUrl is disabled

---

docs/CHANGELOG.md
module.json
views/view/index.php

Before (problem with the corner and background):
After:

Fix Space calendar header

---

Events.php
config.php
controllers/EntryController.php
docs/CHANGELOG.md

https://github.com/humhub/calendar/issues/538

Fix deletion of recurrent calendar entry from wall stream

---

docs/CHANGELOG.md
extensions/custom_pages/elements/CalendarEntryElement.php
extensions/custom_pages/elements/CalendarEventsElement.php
extensions/custom_pages/elements/views/calendars.php
module.json

https://github.com/humhub/custom-pages-internal/issues/4#issuecomment-2724975549

Add filters for template element of the custom pages module

---

composer.json
docs/CHANGELOG.md
module.json

https://github.com/humhub/humhub-internal/issues/684

Fix JWT version conflict with core version

---

controllers/ExportController.php
docs/CHANGELOG.md
helpers/CalendarUtils.php
interfaces/VCalendar.php

https://github.com/humhub/humhub-internal/issues/688

Ical add calendar name

---

docs/CHANGELOG.md
extensions/custom_pages/elements/CalendarEntryElementVariable.php
module.json

https://github.com/humhub/custom-pages-internal/issues/103

Fix extension for module "Custom Pages"

---

.github/workflows/php-test-master.yml
.github/workflows/php-test-min-version.yml
.github/workflows/php-test-next.yml
docs/CHANGELOG.md

https://github.com/humhub/humhub-internal/issues/844

Improved Module Test GitHub Actions
